In [3]:
import numpy as np

def floyd_warshall(graph):
    n = len(graph)
    # Initialize distance matrix
    dist = np.array(graph, dtype=float)

    # Replace 0s (except diagonal) with infinity for no direct path
    dist[dist == 0] = np.inf
    np.fill_diagonal(dist, 0)

    # Perform Floyd-Warshall algorithm
    for k in range(n):
        for i in range(n):
            for j in range(n):
                dist[i, j] = min(dist[i, j], dist[i, k] + dist[k, j])

    return dist

# Example graph as adjacency matrix
graph = [
    [float('inf'), 35, 150, 980, 690, 590],
    [35, float('inf'), 220, 130, 390, 810],
    [150, 220, float('inf'), 25, 930, 490],
    [980, 130, 25, float('inf'), 800, 130],
    [690, 390, 930, 800, float('inf'), 5],
    [590, 810, 490, 130, 5, float('inf')],
]

dist_matrix = floyd_warshall(graph)
print("Shortest distance matrix:")
print(dist_matrix)


Shortest distance matrix:
[[  0.  35. 150. 165. 300. 295.]
 [ 35.   0. 155. 130. 265. 260.]
 [150. 155.   0.  25. 160. 155.]
 [165. 130.  25.   0. 135. 130.]
 [300. 265. 160. 135.   0.   5.]
 [295. 260. 155. 130.   5.   0.]]
